version: '3.8'

services:
  pillsbk-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: pillsbk-backend
    ports:
      - "3001:3001"
    volumes:
      # Monta il volume per persistere il database SQLite
      - ../data:/app/data
      # Volume per i log (opzionale)
      - ../logs:/app/logs
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  data:
    driver: local